config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :events
  post 'events/new', to: 'events#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :user, only: %i[new show]
  post 'user/new', action: 'create', controller: 'user'

  get 'sign_in', to: 'session#new'
  post 'sign_in', to: 'session#create'
  delete 'sign_out', to: 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :event_attendees
  has_many :attendees, class_name: 'User', through: :event_attendees
  validates :name, :description, :date, :venue, presence: true
  scope :upcoming, -> { where('date > ?', Time.now) }
  scope :past, -> { where('date < ?', Time.now) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: :user_id
  belongs_to :attended_event, class_name: 'Event', foreign_key: :event_id
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :email, :password, presence: true

  has_secure_password
  has_many :events
  has_many :event_attendees
  has_many :attended_events, class_name: 'Event', through: :event_attendees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in, except: [:index]
  def new
    @event = Event.new
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash['is-success'] = 'Event created!'
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :description, :venue)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :_signed_in, except: [:destroy]
  def new; end

  def create
    user = User.find_by(username: params[:session][:username])

    if user
      sign_in user
      flash['is-success'] = "Hello #{user.username}!"
      redirect_to user_path(user)
    else
      flash.now['is-danger'] = 'Wrong Credentials!'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @past = @user.attended_events.past
    @upcoming = @user.attended_events.upcoming
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end

  def signed_in
    unless signed_in?
      flash['is-danger'] = 'You must be signed in to access that page!'
      redirect_to sign_in_path

    end
  end

  def _signed_in
    if signed_in?
      flash['is-warning'] = 'You are already signed in!'
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<section class="hero is-info ">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Events
      </h1>
    </div>
  </div>
</section>
<section class="hero  is-white">
  <div class="hero-body">
    <div class="container">
      <div class="columns">
        <div class="column is-desktop">
          <h2 class="title">  Events <div class="tag"><%= Event.all.count%></div> </h2>
        </div>
        <div class="column is-desktop has-text-right">
           <%= link_to 'Create a new event', new_event_path,class: 'button is-primary ' %>
        </div>
      </div>
      
      <div class="columns is-multiline">
        <% Event.all.each do |event| %>
          <div class="column is-12 is-4-desktop">
            <div class="card event">
                        
                <div class="card-content">
                    
                    <div class="content">
                        <p class="title">
                            <%= event.name %>
                        </p>         
                    <div class="subtitle is-size-6">
                        <strong><%= event.date.strftime("%Y/%m/%d") %> at <%= event.venue %></strong>
                        
                    </div>
                    <div class="has-text-right">

                            <%= link_to 'Read more', event_path( event),class: 'button is-link is-light is-small' %>
                        </div>
                    </div>
                </div>

            </div>
          </div>
        <% end %>
        <% if Event.all.count ==0%>
            <div class="column">
                <article class="message is-warning">
                    <div class="message-body">
                        There is no event yet.
                    </div>
                </article>
            </div>
        <%end%>
      </div>
    </div>
  </div>
</section>
<div class="container">
  <div class="columns">
    <div class="column is-6-desktop">
      <section class="hero  is-light">
        <div class="hero-body">
          <div class="container">
            <h2 class="title"> Upcoming Events</h2>
            <div class="columns is-multiline">
              <% Event.upcoming.each do |event| %>
                <div class="column is-12-desktop">
                  <div class="card event">
                        
                    <div class="card-content">
                        
                        <div class="content">
                            <p class="title">
                                <%= event.name %>
                            </p>         
                        <div class="subtitle is-size-6">
                            <strong><%= event.date.strftime("%Y/%m/%d") %> at <%= event.venue %></strong>
                            
                        </div>
                        <div class="has-text-right">

                                <%= link_to 'Read more', event_path( event),class: 'button is-link is-light is-small' %>
                            </div>
                        </div>
                    </div>

                </div>
                </div>
              <% end %>
              <% if Event.upcoming.count ==0%>
                <div class="column">
                    <article class="message is-warning">
                        <div class="message-body">
                            There is no upcoming events yet.
                        </div>
                    </article>
                </div>
              <%end%>
            </div>
          </div>
        </div>
      </section>
    </div>
    <div class="column is-6-desktop">
      <section class="hero  is-light">
        <div class="hero-body">
          <div class="container">
            <h2 class="title"> Past Events</h2>
            <div class="columns is-multiline">
              <% Event.past.each do |event| %>
                <div class="column is-12-desktop">
                  <div class="card event">
                        
                    <div class="card-content">
                        
                        <div class="content">
                            <p class="title">
                                <%= event.name %>
                            </p>         
                        <div class="subtitle is-size-6">
                            <strong><%= event.date.strftime("%Y/%m/%d") %> at <%= event.venue %></strong>
                            
                        </div>
                        <div class="has-text-right">

                                <%= link_to 'Read more', event_path( event),class: 'button is-link is-light is-small' %>
                            </div>
                        </div>
                    </div>

                </div>
                </div>
              <% end %>
              <% if Event.past.count ==0%>
                <div class="column">
                    <article class="message is-warning">
                        <div class="message-body">
                            There is no past events yet.
                        </div>
                    </article>
                </div>
              <%end%>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<section class="hero is-info ">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        New Event
      </h1>
    </div>
  </div>
</section>
<section class="hero  ">
  <div class="hero-body">
    <div class="container">
        <div class="columns">
            <div class="column">
              <%= image_tag 'undraw_online_calendar_kvu2.svg' %>
            </div>
            <div class="column is-6-desktop">
            <% if @event.errors.any? %>
              <div class="notification is-danger is-light">
              <p>The form has the following <%= pluralize(@event.errors.count, 'error')%></p>
                <ul>
                <% @event.errors.full_messages.each do |error| %>
                  <li><%= error %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
              <div class="card">
                <div class="card-content">
        
                  <div class="content">
                    <%= form_for(:event) do |f| %>
          
                      <div class = "field">
                        <%= f.label :name,class: 'label' %>
                        <p class="control">
                          <%= f.text_field :name, class: 'input' %>
                        </p>
                      </div>

                      
                
                      <div class = "field">
                        <%= f.label :description,class:'label' %>
                        <p class="control">
                          <%= f.text_area :description, class: 'input' %>
                        </p>
                      </div>
                      <div class = "field is-horizontal">
                        <div class = "field-body ">
                          
                        </div>
                      </div>
                      <div class = "field">
                            <%= f.label :date,class:'label' %>
                            <p class="control">
                              <%= f.date_field :date, class: 'input' %>
                            </p>
                          </div>
                          <div class = "field">
                            <%= f.label :venue,class:'label' %>
                            <p class="control">
                              <%= f.text_field :venue, class: 'input' %><br />
                            </p>
                          </div>
                      
                      <div class="field">

                        <%= f.submit "Create Event", class: "button is-primary is-block" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            
   
       
    </div>
   
  </div>
</section>

app/views/events/show.html.erb
<section class="hero is-medium is-white home-hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-dark">
        <%= @event.name %>
      </h1>
      <div class="subtitle has-text-dark">
        <div>            
            <%= @event.date.strftime("%Y/%m/%d") %> at <%= @event.venue %>
        </div>
        <div>
            By: <%= @event.creator.username %>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="hero  ">
  <div class="hero-body">
    <div class="container">
    
        <div class="columns">
        <div class="column is-8-desktop">
                <div class="card">
                    <div class="card-content">
                    <div class="title">
                        Description
                    </div>
                    <div class="content">
                        <p><%= @event.description%></p>
                    </div>
                    </div>
                </div>
             
            </div>
            
            <div class="column">
              <div class="card">
                    <div class="card-content">
                    <div class="title">
                        Attendees <span class="tag is-light"><%= @event.attendees.count %></span>
                    </div>
                    <div class="content">
                       <% @event.attendees.each do |attendee|%> 
                            <div class="tag is-light">
                                <%= attendee.username %>
                            </div>
                        <% end %>
                        <% if @event.attendees.count ==0%>
                            <div class="column">
                                <article class="message is-warning">
                                    <div class="message-body">
                                        There is not Attendees for this event yet.
                                    </div>
                                </article>
                            </div>
                        <%end%>
                    </div>
                    </div>
                </div>
             
            </div>
            </div>
            
   
       
    </div>
   
  </div>
</section>

app/views/home/index.html.erb
    <div class="container  has-text-centered">
			<div class="columns">
				<div class="column">
					<section class="hero  is-fullheight  ">
						<div class="hero-body">
							<div class="">

								<h1 class="title  is-size-1">
										Private Events
									</h1>
									<h2 class="subtitle">
										A Simple Ruby On Rails App
									</h2>
									<% if signed_in? %>
									<%= link_to "Go to Panel", user_path(current_user), class: "button  is-success is-large"%>
									<%else%>
									<%= link_to "Getting Started", sign_in_path, class: "button  is-danger is-large"%>
									<%end%>
							</div>
						</div>
					</section>
				</div>
				<div class="column">
					<section class="hero is-fullheight  ">
  					<div class="hero-body">
							<%= image_tag 'undraw_events_2p66.svg' %>
						</div>
					</section>
				</div>
			</div>
     
    </div>
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class=" has-background-light has-navbar-fixed-top" >
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.0/css/bulma.min.css">  

  
  </head>

  <body>
  <%= render '/shared/navbar'%>
  <%= render '/shared/flash'%>

    <%= yield %>
  
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/session/new.html.erb
    <div class="container  ">
			<div class="columns">
				<div class="column">
					<section class="hero  is-fullheight  ">
						<div class="hero-body">
							<div class="container">
                <div class="session-form">
                      <div class="card is-rounded">
                        <div class="card-content">
                          <h1 class="title">Sign Up</h1>        
                            

                            <%= form_for(:session, url: sign_in_path) do |f| %>  
                        
                                <div class="field">
                                    <%= f.label :username,class: 'label'%>
                                    <div class="control">
                                        <%= f.text_field :username, class: 'input' %>
                                    </div>
                                </div>
                                <div class="field">
                                    
                                    <%= f.submit "Sign In", class: 'button is-primary is-block' %>
                                </div>

                                <div class="form-group">
                                </div>
                            <% end %>
                        </div>
                      </div>
                    </div>
							</div>
						</div>
					</section>
				</div>
				<div class="column">
					<section class="hero is-fullheight  ">
  					<div class="hero-body">
							<%= image_tag 'undraw_events_2p66.svg' %>
						</div>
					</section>
				</div>
			</div>
     
    </div>

app/views/shared/_flash.html.erb
<div class="alert-container">
  <% flash.each do |name, msg| %>
    <div class="notification <%= name %> fade show " role="alert">
      <button class="delete" data-target=""></button>
      <%= content_tag :strong, msg.html_safe %>
   
    </div>
  <% end %>
</div>

app/views/shared/_form_errors.html.erb
<% if @user.errors.any? %>
      <div class="notification is-danger is-light">
      <p>The form has the following <%= pluralize(@user.errors.count, 'error')%></p>
        <ul>
        <% @user.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-white is-fixed-top" role="navigation" aria-label="main navigation">
	<div class="container">
	
		<div class="navbar-brand">
			<%= link_to "Private Events", root_path, class: "navbar-item"%>
			

			<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
			</a>
		</div>

		<div id="navbarBasicExample" class="navbar-menu">
			<div class="navbar-start">
				<% if signed_in? %>
					<%= link_to "Home", root_path, class: "navbar-item"%>
					<%= link_to "Panel", user_path(current_user), class: "navbar-item"%>
					<%= link_to "Events", events_path, class: "navbar-item"%>					
				<% end %>
			</div>

			<div class="navbar-end">
				<% if signed_in? %>
					<div class="navbar-item has-dropdown is-hoverable">
						<a class="navbar-link">
							<%= current_user.username %>
						</a>

						<div class="navbar-dropdown">
							<%= link_to "Sign Out",sign_out_path, class: "button is-danger", method: :delete  %>        
							
						</div>
					</div>
				<% else %>
					<div class="navbar-item">
						<div class="buttons">
							<%= link_to "Sign In", sign_in_path, class: "button  is-outlined"%>
							<%= link_to "Sign Up", new_user_path, class: "button is-danger "%>
							
						</div>
					</div>

				<% end %>
			</div>
		</div>
	</div>
</nav>

app/views/static_pages/home.html.erb
    <div class="container  has-text-centered">
			<div class="columns">
				<div class="column">
					<section class="hero  is-fullheight-with-navbar ">
						<div class="hero-body">
							<div class="">

								<h1 class="title  is-size-1">
										Private Events
									</h1>
									<h2 class="subtitle">
										A Simple Ruby On Rails App
									</h2>
									<% if signed_in? %>
									<%= link_to "Go to Panel", user_path(current_user), class: "button  is-success is-large"%>
									<%else%>
									<%= link_to "Getting Started", sign_in_path, class: "button  is-danger is-large"%>
									<%end%>
							</div>
						</div>
					</section>
				</div>
				<div class="column">
					<section class="hero is-fullheight  ">
  					<div class="hero-body">
							<%= image_tag 'undraw_events_2p66.svg' %>
						</div>
					</section>
				</div>
			</div>
     
    </div>
		

app/views/user/new.html.erb
    <div class="container  ">
			<div class="columns">
        <div class="column">
					<section class="hero is-fullheight  ">
  					<div class="hero-body">
							<%= image_tag 'undraw_online_calendar_kvu2.svg' %>
						</div>
					</section>
				</div>
				<div class="column">
					<section class="hero  is-fullheight  ">
						<div class="hero-body">
							<div class="container">
                <div class="session-form">
                      <div class="card is-rounded">
                        <div class="card-content">
                          <%= render '/shared/form_errors'%>
                          <h1 class="title">Sign Up</h1>        
                            <%= form_for(:user) do |f| %>
                              
                              <div class = "field">
                                <%= f.label :username, class: 'label'  %>
                                <div class="control">
                                  <%= f.text_field :username, class: 'input' %>
                                </div>
                              </div>

                              <div class = "field">
                                <%= f.label :email, class: 'label'  %>
                                <div class="control">
                                  <%= f.email_field :email, class: 'input' %>
                                </div>
                              </div>
                            
                              <div class = "field">
                                <%= f.label :password, class: 'label' %>
                                <div class="control">
                                  <%= f.password_field :password, class: 'input' %>
                                </div>
                              </div>
                              
                              <div class = "field">
                                <%= f.label :password_confirmation, "Confirmation",class:'label' %>
                                <div class="control">
                                  
                                  <%= f.password_field :password_confirmation, class: 'input' %><br />
                                </div>
                              </div>

                              <div class="field">

                              <%= f.submit "Create my account", class: "button is-primary is-block" %>
                              </div>
                              
                            <% end %>
                        </div>
                      </div>
                    </div>
							</div>
						</div>
					</section>
				</div>
				
			</div>
     
    </div>

app/views/user/show.html.erb
<section class="hero is-info ">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Dahsboard
      </h1>
    </div>
  </div>
</section>
<section class="hero  is-white">
  <div class="hero-body">
    <div class="container">
        <div class="columns is-desktop">
            <div class="column ">
                <div class="columns">
                    <div class="column is-mobile">
                        <h2 class="title"> My Events <div class="tag"><%= current_user.events.count%></div> </h2>
                    </div>
                    <div class="column is-mobile has-text-right">
                        <%= link_to 'Create a new event', new_event_path,class: 'button is-primary ' %>
                    </div>
                </div>
                
                <div class="columns is-multiline event-list">
                    <% current_user.events.each do |event| %>
                    <div class="column is-12">
                        <div class="card event">
                        
                            <div class="card-content">
                                
                                <div class="content">
                                    <p class="title">
                                        <%= event.name %>
                                    </p>         
                                <div class="subtitle is-size-6">
                                    <strong><%= event.date.strftime("%Y/%m/%d") %> at <%= event.venue %></strong>
                                    
                                </div>
                                <div class="has-text-right">

                                        <%= link_to 'Read more', event_path( event),class: 'button is-link is-light is-small' %>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
            <div class="column is-4-desktop">
                <div class="card">
                        
                        <div class="card-content">
                
                        <div class="content">
                            <table class="table ">

                            <tr>
                                <td>User Name:</td>
                                <td> <%= @user.username %></td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td> <%= @user.email %></td>
                            </tr>
                            <tr>
                                <td>Created at:</td>
                                <td> <%= @user.created_at %></td>
                            </tr>

                        </table>
                        </div>
                        </div>

                    </div>
            </div>
        </div>
    </div>
   
  </div>
</section>
<div class="container">
    <div class="columns">
    <div class="column is-6-desktop">
        <section class="hero  is-light">
            <div class="hero-body">
                <div class="content">
                    <h2 class="title is-size-4"> Upcoming Events</h2>
                    <div class="columns event-list">
                    <% @upcoming.each do |event| %>
                        <div class="column is-12-desktop">
                            <div class="card event">
                        
                                <div class="card-content">
                                    
                                    <div class="content">
                                        <p class="title">
                                            <%= event.name %>
                                        </p>         
                                    <div class="subtitle is-size-6">
                                        <strong><%= event.date.strftime("%Y/%m/%d") %> at <%= event.venue %></strong>
                                    </div>
                                        <div class="has-text-right">

                                        <%= link_to 'Read more', event_path( event),class: 'button is-link is-light is-small' %>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    <% end %>

                    <% if @upcoming.count ==0%>
                        <div class="column">
                            <article class="message">
                                <div class="message-body">
                                    You Have no Upcoming Events to attend!
                                </div>
                            </article>
                        </div>
                    <%end%>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="column is-6-desktop">
        <section class="hero is-small">
            <div class="hero-body">
            <div class="content">
                <h2 class="title is-size-4"> Past Events</h2>
                <div class="columns event-list">
                <% @past.each do |event| %>
                    <div class="column is-12">
                        <div class="card event">
                        
                            <div class="card-content">
                            
                                <div class="content">
                                    <p class="title">
                                        <%= event.name %>
                                    </p>         
                                    <div class="subtitle is-size-6">
                                        <strong><%= event.date.strftime("%Y/%m/%d") %> at <%= event.venue %></strong>
                                    </div>
                                        <div class="has-text-right">

                                        <%= link_to 'Read more', event_path( event),class: 'button is-link is-light is-small' %>
                                        </div>
                                </div>
                            </div>

                        </div>
                    </div>
                <% end %>
                <% if @past.count ==0%>
                    <div class="column">
                        <article class="message is-warning">
                            <div class="message-body">
                                You Have no attended Events.
                            </div>
                        </article>
                    </div>
                <%end%>
                </div>
            </div>
            </div>
        </section>
    </div>
    </div>
</div>